import { getImage } from '../lib';
import type { TPlayer } from '../types';

export const players: TPlayer[] = [
  {
    name: 'Артем',
    tag: 'Слоняра',
    imageSrc: getImage(['players', 'puchkin']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 7,
      accuracy: 6,
      tactics: 8,
      experience: 9,
      communication: 6,
      reaction: 3,
    },
  },
  {
    name: 'Лиза',
    tag: 'Танцовщица',
    imageSrc: getImage(['players', 'shatilova']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 7,
      accuracy: 5,
      tactics: 4,
      experience: 6,
      communication: 8,
      reaction: 4,
    },
  },
  {
    name: 'Кирилл',
    tag: 'Растрыхыч',
    imageSrc: getImage(['players', 'ilyin']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 8,
      accuracy: 3,
      tactics: 6,
      experience: 4,
      communication: 7,
      reaction: 5,
    },
  },
  {
    name: 'Павел',
    tag: 'Бегун',
    imageSrc: getImage(['players', 'pasha']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 9,
      accuracy: 8,
      tactics: 8,
      experience: 8,
      communication: 3,
      reaction: 3,
    },
  },
  {
    name: 'Влад',
    tag: 'Очкарик',
    imageSrc: getImage(['players', 'vlad']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 10,
      communication: 5,
      reaction: 3,
    },
  },
  {
    name: 'Роман',
    tag: 'Отец',
    imageSrc: getImage(['players', 'unknown']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 10,
      communication: 5,
      reaction: 3,
    },
  },
  {
    name: 'Кирилл Ш',
    tag: 'Зануда',
    imageSrc: getImage(['players', 'unknown']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 10,
      communication: 5,
      reaction: 3,
    },
  },
  {
    name: 'Данила',
    tag: 'Малыш',
    imageSrc: getImage(['players', 'danila']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 10,
      communication: 5,
      reaction: 3,
    },
  },
  {
    name: 'Егор',
    tag: 'Галерщик',
    imageSrc: getImage(['players', 'egor']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 10,
      communication: 5,
      reaction: 3,
    },
  },
  {
    name: 'Слава',
    tag: 'Раб AI',
    imageSrc: getImage(['players', 'unknown']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 10,
      communication: 5,
      reaction: 3,
    },
  },
  {
    name: 'Максим',
    tag: 'Чижик',
    imageSrc: getImage(['players', 'max']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 10,
      communication: 5,
      reaction: 3,
    },
  },
  {
    name: 'Матвей',
    tag: 'Биохакер',
    imageSrc: getImage(['players', 'matvej']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 8,
      accuracy: 7,
      tactics: 10,
      experience: 8,
      communication: 8,
      reaction: 7,
    },
  },
  {
    name: 'Александра',
    tag: 'Новенькая',
    imageSrc: getImage(['players', 'egorova']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 3,
      communication: 2,
      reaction: 3,
    },
  },
  {
    name: 'Александр',
    tag: 'Карп',
    imageSrc: getImage(['players', 'karp']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 8,
      experience: 1,
      communication: 8,
      reaction: 3,
    },
  },
  {
    name: 'Артем',
    tag: 'Аналитик',
    imageSrc: getImage(['players', 'unknown']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 5,
      tactics: 2,
      experience: 4,
      communication: 8,
      reaction: 5,
    },
  },
  {
    name: 'Артем',
    tag: 'Фронтик',
    imageSrc: getImage(['players', 'petrov']),
    description: 'Молодой, веселый бармолей',
    characteristics: {
      physical: 5,
      accuracy: 2,
      tactics: 9,
      experience: 6,
      communication: 7,
      reaction: 5,
    },
  },
];
